# Generated by Django 5.2.4 on 2025-12-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='aulaApp.asignatura'),
        ),
    ]
