# Generated by Django 5.2.4 on 2025-12-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0003_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasesagendadas',
            name='datos_pizarra',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
