# Generated by Django 5.2.4 on 2025-12-07 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0004_clasesagendadas_datos_pizarra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='dia',
        ),
    ]
