# Generated by Django 5.2.4 on 2026-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0005_alter_disponibilidad_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasesagendadas',
            name='oculto_para_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='oculto_para_estudiante',
            field=models.BooleanField(default=False),
        ),
    ]
