# Generated by Django 5.2.4 on 2026-05-09 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0006_clasesagendadas_oculto_para_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasesagendadas',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='clasesagendadas',
            name='datos_pizarra',
        ),
        migrations.RemoveField(
            model_name='clasesagendadas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clasesagendadas',
            name='oculto_para_docente',
        ),
        migrations.RemoveField(
            model_name='clasesagendadas',
            name='oculto_para_estudiante',
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clase_registrada', to='aulaApp.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='clasesagendadas',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clasesagendadas',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clasesagendadas',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_estudiante', to=settings.AUTH_USER_MODEL),
        ),
    ]
