# Generated by Django 5.2.4 on 2026-05-09 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0007_remove_clasesagendadas_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasesagendadas',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aulaApp.asignatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='estado',
            field=models.CharField(default='AGEN', max_length=20),
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='oculto_para_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='oculto_para_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasesagendadas',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DisponibilidadMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la repetición semanal')),
                ('fecha_fin', models.DateField(help_text='Fecha de término de la repetición semanal')),
                ('dia_semana', models.IntegerField(help_text='1=Lunes, 2=Martes, ..., 7=Domingo')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_multiples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
