# Generated by Django 5.2.4 on 2026-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0008_clasesagendadas_asignatura_clasesagendadas_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasesagendadas',
            name='datos_pizarra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
