# Generated by Django 5.2.4 on 2026-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaApp', '0009_clasesagendadas_datos_pizarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasesagendadas',
            name='historial_chat',
            field=models.TextField(default='[]'),
        ),
    ]
